global:
  scrape_interval: "5s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "node_exporter:9100"
  - job_name: "postgres_exporter"
    static_configs:
      - targets:
          - "postgres_exporter:9187"
  - job_name: "push_gateway"
    static_configs:
      - targets:
          - "push_gateway:9091"
  - job_name: "app_one"
    static_configs:
      - targets:
          - "app_one:8000"
  - job_name: "pmon"
    static_configs:
    - targets: 
          - "pmon:8089"
  - job_name: "bookinfo"
    static_configs:
    - targets: 
          - "35.224.0.241:9080"

