apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shippingservice
spec:
  hosts:
  - shippingservice
  http:
  - match:
    - sourceLabels:
        app: "frontend"
    fault:
      delay:
        fixedDelay: .2s
        percent: 100 
    route:
      - destination:
          host: shippingservice       
  - route:
    - destination:
        host: shippingservice
